### PR TITLE
Homepage redesign - zoom out effect

### PR DESCRIPTION
**Pull request by alireza-ahmadi**
I have applied the zoom out effect to your redesign. There are still lots of work, especially for the mobile browsers, but I have created the pull request to check that are you agree with this effect or not. I will try to fix navigation on mobile devices as soon as possible.

### CODE REVIEW

**Comment by digitalcraftsman** [comment]
Nice to hear from you. This effect looks good and is something different than the usual parallex effect. What are the next parts of the website that you would like to redesign and in which way?

**Comment by alireza-ahmadi** [comment]
My short term goals:
- Fix mobile navigation of the website
- Making other buttons round to look as same as hero section
- Apply minor improvements to fonts, colors, etc.
And in long term we can plan for improving design across all pages of the website. But as we discussed before, It's better to improve current design without applying fundamental changes first.

**Comment by digitalcraftsman** [comment]
You seem to try to implement a mobile-friendly navigation. Then I could focus on the buttons within the next days since I work simultainiously on some new features in Hugo itself.

**Comment by alireza-ahmadi** [comment]
And also I think we should apply a refactor on frontend code base of Hugo. The code base does not follow a convention for naming files and coding. This makes contribution hard.

**Comment by digitalcraftsman** [comment]
Do you have a special naming pattern in mind, something like BEM? Or in which direction do you tend?

**Pull request merged**
